In [1]:
from numpy import array
from scipy.linalg import svd

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [2]:
A = array([[1,2],[3,4],[5,4]])

In [3]:
print(A)

[[1 2]
 [3 4]
 [5 4]]


In [4]:
U, s, VT= svd(A)

In [8]:
print(U)

[[-0.25506667 -0.56529318 -0.78446454]
 [-0.5943241  -0.54829282  0.58834841]
 [-0.76270561  0.61629425 -0.19611614]]


In [6]:
print(s)

[8.33688649 1.22324312]


In [7]:
print(VT)

[[-0.70188878 -0.71228656]
 [ 0.71228656 -0.70188878]]


In [9]:
from numpy import diag
from numpy import dot
from numpy import zeros

In [11]:
Sigma=zeros((A.shape[0], A.shape[1]))

In [12]:
Sigma[:A.shape[1], : A.shape[1]]=diag(s)

In [13]:
B=U.dot(Sigma.dot(VT))

In [14]:
print(B)

[[1. 2.]
 [3. 4.]
 [5. 4.]]


In [15]:
A=array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
U, s, VT=svd(A)

In [18]:
print(U)

[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]


In [19]:
print(s)

[1.68481034e+01 1.06836951e+00 3.33475287e-16]


In [20]:
print(VT)

[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [21]:
Sigma=diag(s)

In [22]:
B=U.dot(Sigma.dot(VT))

In [23]:
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [24]:
from numpy.linalg import pinv

In [25]:
A=array([[.1,.2],[.3,.4],[.5,.6],[.7,.8]])

In [26]:
print(A)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]


In [27]:
B=pinv(A)

In [29]:
print(B)

[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [30]:
from numpy.linalg import svd

In [31]:
U, s, VT= svd(A)

In [32]:
d=1.0/s

In [33]:
D=zeros(A.shape)

In [34]:
D[:A.shape[1], :A.shape[1]]=diag(d)

In [35]:
B=VT.T.dot(D.T).dot(U.T)

In [36]:
print(B)

[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [37]:
A=array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
    
])

In [38]:
U,s, VT= svd(A)

In [39]:
Sigma= zeros((A.shape[0], A.shape[1]))

In [40]:
Sigma[:A.shape[0], : A.shape[0]]=diag(s)

In [41]:
n_elements=2

In [42]:
Sigma=Sigma[: , : n_elements]

In [44]:
VT=VT[:n_elements,:]

In [45]:
B=U.dot(Sigma.dot(VT))

In [46]:
T=U.dot(Sigma)

In [47]:
T=A.dot(VT.T)

In [48]:
B

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [49]:
print(T)

[[-18.52157747  -6.47697214]
 [-49.81310011  -1.91182038]
 [-81.10462276   2.65333138]]
