In [1]:
from __feature__ import print_function

ModuleNotFoundError: No module named '__feature__'

In [2]:
from __future__ import print_function

In [3]:
import torch

In [4]:
torch.empty(5,3)

tensor([[1.0194e-38, 9.6429e-39, 9.2755e-39],
        [9.1837e-39, 9.3674e-39, 1.0745e-38],
        [1.0653e-38, 9.5510e-39, 1.0561e-38],
        [1.0194e-38, 1.1112e-38, 1.0561e-38],
        [9.9184e-39, 1.0653e-38, 4.1327e-39]])

In [5]:
x=torch.empty(5,3)

In [6]:
print(x)

tensor([[9.6429e-39, 9.2755e-39, 1.0286e-38],
        [9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 1.0194e-38, 9.0919e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [9.6429e-39, 1.0745e-38, 9.6429e-39]])


In [7]:
torch.rand(5,3)

tensor([[0.6955, 0.4230, 0.6481],
        [0.9714, 0.2445, 0.8331],
        [0.0569, 0.4878, 0.1442],
        [0.5783, 0.6116, 0.8714],
        [0.8108, 0.6644, 0.6611]])

In [8]:
x=torch.tensor([3,3])

In [9]:
print(x)

tensor([3, 3])


In [10]:
x=x.new_ones(5,3, dtype=torch.double)

In [11]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x=torch.randn_like(x, dtype=torch.float)

In [13]:
print(x)

tensor([[ 0.3548, -0.9843,  1.0395],
        [ 0.4641,  1.0412,  1.0259],
        [-0.3296,  1.0544,  0.1933],
        [-1.4520,  0.0447,  0.2328],
        [-0.1825, -0.1659,  0.0530]])


In [14]:
print(x.size())

torch.Size([5, 3])


In [15]:
y=torch.rand(5,3)

In [16]:
print(x+y)

tensor([[ 0.4641, -0.1916,  1.6505],
        [ 0.5848,  1.7887,  1.8191],
        [-0.3284,  1.4668,  0.6208],
        [-1.3006,  0.1169,  0.2701],
        [ 0.4879,  0.0166,  0.3532]])


In [19]:
x=2.0
y=3.0

In [20]:
x.add_(y)

AttributeError: 'float' object has no attribute 'add_'

In [21]:
x=torch.ones(2,2)

In [22]:
y=torch.randn(2,2)

In [23]:
x.add_(y)

tensor([[-1.4434,  2.6617],
        [-0.2219,  1.0885]])

In [24]:
print(x)

tensor([[-1.4434,  2.6617],
        [-0.2219,  1.0885]])


In [25]:
x=torch.randn(4,4)

In [26]:
y=x.view(16)

In [27]:
z=x.view(-1,8)

In [28]:
print(x.size())

torch.Size([4, 4])


In [29]:
print(y.size())

torch.Size([16])


In [30]:
print(z.size())

torch.Size([2, 8])


In [31]:
x=torch.randn(1)

In [32]:
print(x)

tensor([0.8067])


In [33]:
print(x.item())

0.8066797256469727


In [34]:
a=torch.ones(5)

In [35]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [36]:
b=a.numpy()

In [37]:
print(b)

[1. 1. 1. 1. 1.]


In [38]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [39]:
print(a)

tensor([2., 2., 2., 2., 2.])


In [40]:
print(b)

[2. 2. 2. 2. 2.]


In [41]:
import numpy as np

In [42]:
a=np.ones(5)

In [43]:
b=torch.from_numpy(a)

In [44]:
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [45]:
np.add(a,1, out=a)

array([2., 2., 2., 2., 2.])

In [46]:
print(a)

[2. 2. 2. 2. 2.]


In [47]:
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [48]:
x=torch.ones(2,2, requires_grad=True)

In [49]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [50]:
y=x+2

In [51]:
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [52]:
print(y.grand_fn)

AttributeError: 'Tensor' object has no attribute 'grand_fn'

In [53]:
print(y.grad_fn)

In [54]:
z=y*y*3

out=z.mean()

In [55]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [56]:
a=torch.randn(2,2)
a=((a*3)/ (a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [57]:
out.backward()

C:\Users\User\anaconda3\lib\site-packages\torch\autograd\__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


In [58]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [59]:
x=torch.randn(3, requires_grad=True)
y=x*2
while y.data.norm() <1000:
    y=y*2
print(y)

tensor([ -365.7036, -1041.8802,   404.0877], grad_fn=<MulBackward0>)


In [60]:
v=torch.tensor([0.1, 1.0, .0001], dtype=torch.float)
y.backward(v)

In [61]:
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])
