In [1]:
import torch

In [2]:
x=torch.empty(5,3)

In [3]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
x=torch.rand(5,3)

In [5]:
x

tensor([[0.9386, 0.4341, 0.3348],
        [0.6929, 0.4106, 0.0875],
        [0.2375, 0.1524, 0.2258],
        [0.3326, 0.1819, 0.9504],
        [0.2009, 0.8424, 0.3454]])

In [7]:
x=torch.zeros(5,3, dtype=torch.long)

In [8]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [9]:
x=torch.tensor([5.5, 3])

In [10]:
x

tensor([5.5000, 3.0000])

In [11]:
x=x.new_ones(5,3, dtype=torch.double)

In [12]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [13]:
x=torch.rand_like(x, dtype=torch.float)

In [14]:
x

tensor([[0.3716, 0.7369, 0.6132],
        [0.7337, 0.0388, 0.2330],
        [0.3324, 0.0609, 0.8628],
        [0.2796, 0.7165, 0.7406],
        [0.5942, 0.5630, 0.4929]])

In [15]:
x.size()

torch.Size([5, 3])

In [16]:
y=torch.rand(5,3)

In [17]:
x+y

tensor([[0.7257, 0.9782, 1.0274],
        [1.0383, 0.2971, 1.1379],
        [1.0633, 0.4692, 1.5029],
        [0.5052, 0.8070, 0.9192],
        [1.5498, 1.2611, 1.4869]])

In [18]:
torch.add(x+y)

TypeError: add() received an invalid combination of arguments - got (Tensor), but expected (Tensor input, Tensor other, *, Number alpha, Tensor out)

In [19]:
x=torch.rand(5,3)

In [20]:
y=torch.rand(5,3)

In [21]:
torch.add(x+y)

TypeError: add() received an invalid combination of arguments - got (Tensor), but expected (Tensor input, Tensor other, *, Number alpha, Tensor out)

In [22]:
result=torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[0.9534, 1.4600, 1.4281],
        [1.3480, 0.3230, 1.5041],
        [0.7477, 1.2444, 0.7403],
        [0.6010, 0.7989, 1.3592],
        [0.9005, 1.1155, 0.5790]])


In [23]:
y.add_(x)

tensor([[0.9534, 1.4600, 1.4281],
        [1.3480, 0.3230, 1.5041],
        [0.7477, 1.2444, 0.7403],
        [0.6010, 0.7989, 1.3592],
        [0.9005, 1.1155, 0.5790]])

In [24]:
y

tensor([[0.9534, 1.4600, 1.4281],
        [1.3480, 0.3230, 1.5041],
        [0.7477, 1.2444, 0.7403],
        [0.6010, 0.7989, 1.3592],
        [0.9005, 1.1155, 0.5790]])

In [25]:
print(x[:,1])

tensor([0.7594, 0.1177, 0.8411, 0.0194, 0.6580])


In [26]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [27]:
x=torch.randn(1)

In [28]:
print(x)

tensor([0.2697])


In [29]:
print(x.item())

0.2697303593158722


In [30]:
a=torch.ones(5)

In [31]:
a

tensor([1., 1., 1., 1., 1.])

In [32]:
b=a.numpy()

In [33]:
print(b)

[1. 1. 1. 1. 1.]


In [34]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [35]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [37]:
# converting torch tensor to numpy array

In [40]:
a=torch.ones(5)

In [41]:
a

tensor([1., 1., 1., 1., 1.])

In [42]:
b=a.numpy()

In [43]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [44]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [45]:
a

tensor([2., 2., 2., 2., 2.])

In [46]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [64]:
b+1

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)

In [65]:
a

array([2., 2., 2., 2., 2.])

In [47]:
#converting numpy array to torch tensor

In [48]:
import numpy as np

In [56]:
a=np.ones(5)

In [57]:
a

array([1., 1., 1., 1., 1.])

In [58]:
b=torch.from_numpy(a)

In [59]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [60]:
b.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [61]:
a

array([2., 2., 2., 2., 2.])

In [62]:
a+1

array([3., 3., 3., 3., 3.])

In [63]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)